const APPEND = 'PRODUCT/APPEND';
const CLEAR = 'PRODUCT/CLEAR';
const SET_PAGE = 'PRODUCT/SET_PAGE';
const SET_ITEM_COUNT = 'PRODUCT/SET_ITEM_COUNT';
const INCREASE_ITEM_COUNT = 'PRODUCT/INCREASE_ITEM_COUNT';
const SET_TOTAL_ITEM_COUNT = 'PRODUCT/SET_TOTAL_ITEM_COUNT';

export {
  APPEND,
  CLEAR,
  SET_PAGE,
  SET_ITEM_COUNT,
  INCREASE_ITEM_COUNT,
  SET_TOTAL_ITEM_COUNT,
};
